const donors = [
    {
      name: "Sanjeev Kumar",
      bloodGroup: "O+",
      donationType: "Plasma",
      units: 2,
      status: "Critical",
      hospital: "IGIMS",
      city: "Sheikhpura",
      state: "Bihar",
      country: "India",
      date: "Tuesday, Dec 31",
      acceptButtonText: "Accept",
    },
    {
      name: "Priya Patel",
      bloodGroup: "A+",
      donationType: "Blood",
      units: 1,
      status: "Stable",
      hospital: "AIIMS",
      city: "Delhi",
      state: "Delhi",
      country: "India",
      date: "Monday, Dec 30",
      acceptButtonText: "Accept",
    },
    {
      name: "Ravi Verma",
      bloodGroup: "B+",
      donationType: "Plasma",
      units: 3,
      status: "Critical",
      hospital: "KGMU",
      city: "Lucknow",
      state: "Uttar Pradesh",
      country: "India",
      date: "Sunday, Dec 29",
      acceptButtonText: "Accept",
    },
    {
      name: "Anjali Sharma",
      bloodGroup: "AB+",
      donationType: "Blood",
      units: 1,
      status: "Critical",
      hospital: "PGI",
      city: "Chandigarh",
      state: "Punjab",
      country: "India",
      date: "Saturday, Dec 28",
      acceptButtonText: "Accept",
    },
    {
      name: "Vikas Singh",
      bloodGroup: "O-",
      donationType: "Blood",
      units: 1,
      status: "Stable",
      hospital: "CMC",
      city: "Vellore",
      state: "Tamil Nadu",
      country: "India",
      date: "Friday, Dec 27",
      acceptButtonText: "Accept",
    },
  ];
  
  export default donors